name: GenFusion
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - ffmpeg=4.3
  - numpy=1.24.3
  - pytorch=2.1.1
  - pyyaml=6.0.2
  - torchaudio=2.1.1
  - pytorch-cuda=12.1
  - torchtriton=2.1.0
  - torchvision=0.16.1
  - pip=23.3.1
  - pip:
      - av==12.3.0
      - accelerate==1.0.1
      - diffusers==0.31.0
      - einops==0.8.0
      - ffmpeg-python==0.2.0
      - open-clip-torch==2.12.0
      - flask==3.0.3
      - gsplat==1.4.0
      - huggingface-hub==0.26.2
      - imageio==2.35.1
      - kornia==0.7.3
      - lightning==2.3.3
      - lpips==0.1.4
      - matplotlib==3.7.5
      - omegaconf==2.3.0
      - open-clip-torch==2.12.0
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - pandas==2.0.3
      - plyfile==1.0.3
      - pytorch-lightning==2.4.0
      - pytorch-msssim==1.0.0
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - tensorboard==2.14.0
      - torch-fidelity==0.3.0
      - torchmetrics==1.5.1
      - tqdm==4.66.2
      - transformers==4.46.2
      - trimesh==4.3.2
      - xformers==0.0.23
      - git+https://github.com/rmbrualla/pycolmap@cc7ea4b7301720ac29287dbe450952511b32125e
      - mediapy==1.1.2
    

